name: Build and Publish
on: [push]
jobs:
  publish-todo-app-server-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./server
          tags: |
            ghcr.io/charles-hl/todo-app-server:latest
            ghcr.io/charles-hl/todo-app-server:1.0.0
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
